version: '3.3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
#      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
