version: '3.3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    links:
      - backend
    ports:
      - '8080:8080'
    expose:
      - '8080'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    links:
      - db
    ports:
      - "5000:5000"
    expose:
      - '5000'
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
#      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
